# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../../../lib", __dir__))
require "unicode/data"

desc "Download the unicode data file necessary for the current version of Ruby"
task :default do
  Unicode::Data.generate
end
